#!/bin/sh
#
# Solarized color scheme for the Linux console
# Executable script to send the required escape sequences to the terminal.
#
# Author: Alexandre de Verteuil
# Date: 2013-09-21
# URL: https://github.com/adeverteuil/console-solarized
# Main Solarized project URL: http://ethanschoonover.com/solarized
#
# This file should be placed in the PATH, such as "/usr/local/bin".
# It will be executed from the console-solarized@.service unit
# when a getty@.service unit is instantiated.
#
# See man 4 console_codes for more information.

TERM=linux

echo() {
  env echo $*
}

# RGB values

S_base03="002b36"
S_base02="073642"
S_base01="586e75"
S_base00="657b83"
S_base0="839496"
S_base1="93a1a1"
S_base2="eee8d5"
S_base3="fdf6e3"
S_yellow="b58900"
S_orange="cb4b16"
S_red="dc322f"
S_magenta="d33682"
S_violet="6c71c4"
S_blue="268bd2"
S_cyan="2aa198"
S_green="859900"

if [ -n "$1" ]; then
	conf=$1
elif [ -f /etc/console-solarized.conf ]; then
	. /etc/console-solarized.conf
	conf=$THEME
fi

case "$conf" in
    light)

        # Light

        S_rebase03="$S_base3"
        S_rebase02="$S_base2"
        S_rebase01="$S_base1"
        S_rebase00="$S_base0"
        S_rebase0="$S_base00"
        S_rebase1="$S_base01"
        S_rebase2="$S_base02"
        S_rebase3="$S_base03"

	;;

    dark)

        # Dark

        S_rebase03="$S_base03"
        S_rebase02="$S_base02"
        S_rebase01="$S_base01"
        S_rebase00="$S_base00"
        S_rebase0="$S_base0"
        S_rebase1="$S_base1"
        S_rebase2="$S_base2"
        S_rebase3="$S_base3"

	;;

    *)

        # invalid configuration

        exit 1

	;;
esac

printf "\033]P0$S_rebase02" # Black
printf "\033]P1$S_red"      # Red
printf "\033]P2$S_green"    # Green
printf "\033]P3$S_yellow"   # Brown
printf "\033]P4$S_blue"     # Blue
printf "\033]P5$S_magenta"  # Magenta
printf "\033]P6$S_cyan"     # Cyan
printf "\033]P7$S_rebase2"  # White
printf "\033]P8$S_rebase03"
printf "\033]P9$S_orange"
printf "\033]Pa$S_rebase01"
printf "\033]Pb$S_rebase00"
printf "\033]Pc$S_rebase0"
printf "\033]Pd$S_violet"
printf "\033]Pe$S_rebase1"
printf "\033]Pf$S_rebase3"

# SOLARIZED HEX     16/8 TERMCOL  XTERM/HEX   L*A*B      RGB         HSB
# --------- ------- ---- -------  ----------- ---------- ----------- -----------
# base03    #002b36  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21
# base02    #073642  0/4 black    235 #262626 20 -12 -12   7  54  66 192  90  26
# base01    #586e75 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46
# base00    #657b83 11/7 bryellow 241 #626262 50 -07 -07 101 123 131 195  23  51
# base0     #839496 12/6 brblue   244 #808080 60 -06 -03 131 148 150 186  13  59
# base1     #93a1a1 14/4 brcyan   245 #8a8a8a 65 -05 -02 147 161 161 180   9  63
# base2     #eee8d5  7/7 white    254 #e4e4e4 92 -00  10 238 232 213  44  11  93
# base3     #fdf6e3 15/7 brwhite  230 #ffffd7 97  00  10 253 246 227  44  10  99
# yellow    #b58900  3/3 yellow   136 #af8700 60  10  65 181 137   0  45 100  71
# orange    #cb4b16  9/3 brred    166 #d75f00 50  50  55 203  75  22  18  89  80
# red       #dc322f  1/1 red      160 #d70000 50  65  45 220  50  47   1  79  86
# magenta   #d33682  5/5 magenta  125 #af005f 50  65 -05 211  54 130 331  74  83
# violet    #6c71c4 13/5 brmagenta 61 #5f5faf 50  15 -45 108 113 196 237  45  77
# blue      #268bd2  4/4 blue      33 #0087ff 55 -10 -45  38 139 210 205  82  82
# cyan      #2aa198  6/6 cyan      37 #00afaf 60 -35 -05  42 161 152 175  74  63
# green     #859900  2/2 green     64 #5f8700 60 -20  65 133 153   0  68 100  60
