#!/usr/bin/sh
#
# Solarized color scheme for the Linux console
# Executable script to send the required escape sequences to the terminal.
#
# Author: Alexandre de Verteuil
# Date: 2013-09-21
# URL: https://github.com/adeverteuil/console-solarized
# Main Solarized project URL: http://ethanschoonover.com/solarized
#
# This file should be placed in the PATH, such as "/usr/local/bin".
# It will be executed from the console-solarized-{light,dark}@.service unit
# when a getty@.service unit is instantiated.
#
# See man 4 console_codes for more information.

TERM=linux

# Common

S_yellow="b58900"
S_orange="cb4b16"
S_red="dc322f"
S_magenta="d33682"
S_violet="6c71c4"
S_blue="268bd2"
S_cyan="2aa198"
S_green="859900"

if [ "$1x" == "lightx" ]; then

    # Light

    S_base03="fdf6e3"
    S_base02="eee8d5"
    S_base01="93a1a1"
    S_base00="839496"
    S_base0="657b83"
    S_base1="586e75"
    S_base2="073642"
    S_base3="002b36"
else

    # Dark

    S_base03="002b36"
    S_base02="073642"
    S_base01="586e75"
    S_base00="657b83"
    S_base0="839496"
    S_base1="93a1a1"
    S_base2="eee8d5"
    S_base3="fdf6e3"
fi

echo -en "\e]P0$S_base02"   # Black
echo -en "\e]P1$S_red"      # Red
echo -en "\e]P2$S_green"    # Green
echo -en "\e]P3$S_yellow"   # Brown
echo -en "\e]P4$S_blue"     # Blue
echo -en "\e]P5$S_magenta"  # Magenta
echo -en "\e]P6$S_cyan"     # Cyan
echo -en "\e]P7$S_base2"    # White
echo -en "\e]P8$S_base03"
echo -en "\e]P9$S_orange"
echo -en "\e]Pa$S_base01"
echo -en "\e]Pb$S_base00"
echo -en "\e]Pc$S_base0"
echo -en "\e]Pd$S_violet"
echo -en "\e]Pe$S_base1"
echo -en "\e]Pf$S_base3"

# SOLARIZED HEX     16/8 TERMCOL  XTERM/HEX   L*A*B      RGB         HSB
# --------- ------- ---- -------  ----------- ---------- ----------- -----------
# base03    #002b36  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21
# base02    #073642  0/4 black    235 #262626 20 -12 -12   7  54  66 192  90  26
# base01    #586e75 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46
# base00    #657b83 11/7 bryellow 241 #626262 50 -07 -07 101 123 131 195  23  51
# base0     #839496 12/6 brblue   244 #808080 60 -06 -03 131 148 150 186  13  59
# base1     #93a1a1 14/4 brcyan   245 #8a8a8a 65 -05 -02 147 161 161 180   9  63
# base2     #eee8d5  7/7 white    254 #e4e4e4 92 -00  10 238 232 213  44  11  93
# base3     #fdf6e3 15/7 brwhite  230 #ffffd7 97  00  10 253 246 227  44  10  99
# yellow    #b58900  3/3 yellow   136 #af8700 60  10  65 181 137   0  45 100  71
# orange    #cb4b16  9/3 brred    166 #d75f00 50  50  55 203  75  22  18  89  80
# red       #dc322f  1/1 red      160 #d70000 50  65  45 220  50  47   1  79  86
# magenta   #d33682  5/5 magenta  125 #af005f 50  65 -05 211  54 130 331  74  83
# violet    #6c71c4 13/5 brmagenta 61 #5f5faf 50  15 -45 108 113 196 237  45  77
# blue      #268bd2  4/4 blue      33 #0087ff 55 -10 -45  38 139 210 205  82  82
# cyan      #2aa198  6/6 cyan      37 #00afaf 60 -35 -05  42 161 152 175  74  63
# green     #859900  2/2 green     64 #5f8700 60 -20  65 133 153   0  68 100  60
